### ISSUE TITLE
[GitFlick] - code review by Marika & Lucy

### ISSUE THREAD

**Issue by lucfercas** [FAC29A/code-reviews#11]
### README

[Does the README describe the project using the subheadings: Why?, What?, How? i.e. Why have you created this repo, what does it do, how does it do it?]

- Yes, it covers all the requirements and presents the project well. If I needed extra guidance, a step by step or 'first steps' section would have been great: 'Do this to get started, then do that'.

### User stories

[Does the project meet the user stories for that week?]

- Yes, they do.

### Learning outcomes

[Does it demonstrate the learning outcomes for that week?]

- Yes, definitely. All APIs are functional, there are no errors in sight. 

### UI bugs

[Can you see any obvious bugs or areas to improve?]

- Only one: the footer search function is not properly styled. Nothing major though. 
Improvement suggestion: Maybe increase the padding in the search bar (so the text input is seen more clearly).

### Instructions

[Does everything work as expected or were there missing instructions?]
- While we appreciated the instructions to clone the repo, a basic step by step list describing the app's usage is always welcome. It helps to better understand its purpose and usability. 

### File structure

[When you open the project in your editor, does the file structure make sense?]
- Yes, the files make sense and are properly organised.

### Flow of control

[ Can you you follow the different paths the code might take?]
- Mostly yes, we would have liked to see some comments explaining the beginning of the code in the js file, the rest of the file was very well described and commented. 

### Naming

[Do variables and functions have clear and descriptive names?]
- Yes, very good job!

### Readability

[Do you understand the code?]
- Yes, the code is clean and well structured.

**Comment by Paing-Ko** [comment]
Fixed the issues
