### ISSUE TITLE
Marika_Lucy_App - code review

### ISSUE THREAD

**Issue by DanielMA7** [FAC29A/code-reviews#12]
### README

The ReadME still needs updating.

### User stories

Yes the project meets the user stories

### Learning outcomes

Yes the project meets the learning outcomes

### UI bugs

There are no UI bugs that we can find

### Instructions

There are missing data from the table.

### File structure

Yes the files are organised correctly and the structure makes sense.

### Flow of control

Yes the flow of the code is good.

### Naming

Yes the variables and functions are very clearly named.

### Readability

Yes the code is understandable and very well organised.

**Comment by lucfercas** [comment]
All sorted
