### ISSUE TITLE
ecoecho (Marika & Paing) - code review

### ISSUE THREAD

**Issue by lucfercas** [FAC29A/code-reviews#2]
### README

[Does the README describe the project using the subheadings: Why?, What?, How? i.e. Why have you created this repo, what does it do, how does it do it?]
It does describe the project briefly, but we are missing some more details and specifics (How is that VR experience embedded into the website? Or the best way to use the website?) It does explain very well how to access the webpage.

### User stories

[Does the project meet the user stories for that week?]
Yes, definitely.

### Learning outcomes

[Does it demonstrate the learning outcomes for that week?]
We believe so.

### UI bugs

[Can you see any obvious bugs or areas to improve?]
The background video needs resizing, and maybe media queries. Same with the header image. 

### Instructions

[Does everything work as expected or were there missing instructions?]
All works well and it's fully operational.

### File structure

[When you open the project in your editor, does the file structure make sense?]
It is well structured and makes sense. If we had to suggest anything it would be to separate the types of media used between videos and images. 

### Flow of control

[ Can you you follow the different paths the code might take?]
Yes

### Naming

[Do variables and functions have clear and descriptive names?]
Yes.

### Readability

[Do you understand the code?]
Daniel: Yes, it is clear and labeled well.
Lucy: I do understand most of it, but not all. I do however appreciate the labels and descriptive division of parts in the code.

**Comment by Paing-Ko** [comment]
I fixed the issue except Background video and header image resizing.
