### ISSUE TITLE
Crazy-agency - code review

### ISSUE THREAD

**Issue by MarikaBBB** [FAC29A/code-reviews#6]
https://github.com/lucfercas/Crazy-agency.git

DISCLAIMER: The project is a draft.

### README

[Does the README describe the project using the subheadings: Why?, What?, How? i.e. Why have you created this repo, what does it do, how does it do it?]
It's a work in progress.

### User stories

[Does the project meet the user stories for that week?]
Yes but they need to style it

### Learning outcomes

[Does it demonstrate the learning outcomes for that week?]
Yes, I can see you use javascript to generate the team members section and you have the contact form done.

### UI bugs

[Can you see any obvious bugs or areas to improve?]
The video takes a lot of time to load.

### Instructions

[Does everything work as expected or were there missing instructions?]
It's a work in progress

### File structure

[When you open the project in your editor, does the file structure make sense?]

### Flow of control

[ Can you follow the different paths the code might take?]
Yes, we clearly follow the different sections of all the files.

### Naming
[Do variables and functions have clear and descriptive names?]

### Readability

[Do you understand the code?]
HTML need space between different parts to be more readable.

**Comment by lucfercas** [comment]
We implemented the changes and finished our website, thanks!
